from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from .extraction import ExtractionService
from .markdown import atomic_write_text, read_document
from .repository import Repository


GENERATOR = "gm-obsidian-v2"


class ObsidianViewService:
    """Build disposable, human-readable Obsidian views without changing truth layers."""

    def __init__(self, repository: Repository):
        self.repository = repository
        self.extractions = ExtractionService(repository)

    def _documents(self) -> list[tuple[Path, dict[str, Any]]]:
        documents = [(path, read_document(path)[0]) for path in self.repository.canonical_documents()]
        return sorted(documents, key=lambda item: (str(item[1].get("type", "")), self._title(item[1])))

    def _sources(self) -> list[tuple[Path, dict[str, Any], str]]:
        sources = []
        for path in self.repository.source_documents():
            metadata, body = read_document(path)
            sources.append((path, metadata, body))
        return sorted(
            sources,
            key=lambda item: str(item[1].get("captured_at") or item[1].get("created_at") or ""),
            reverse=True,
        )

    @staticmethod
    def _title(metadata: dict[str, Any]) -> str:
        return str(metadata.get("title") or metadata.get("original_title") or metadata.get("id") or "未命名")

    def _link(self, path: Path, metadata: dict[str, Any]) -> str:
        relative = self.repository.rel(path).removeprefix("vault/").removesuffix(".md")
        return f"[[{relative}|{self._title(metadata)}]]"

    @staticmethod
    def _header(title: str, description: str = "") -> str:
        lead = f"# {title}\n\n"
        if description:
            lead += f"> {description}\n\n"
        return f"<!-- generated by {GENERATOR}; safe to rebuild -->\n\n{lead}"

    @staticmethod
    def _date(metadata: dict[str, Any]) -> str:
        value = str(metadata.get("published_at") or metadata.get("captured_at") or metadata.get("created_at") or "")
        return value[:10] or "日期未知"

    @staticmethod
    def _reader_relative(source_id: str) -> str:
        return f"vault/views/readers/{source_id}.md"

    def _reader_link(self, metadata: dict[str, Any]) -> str:
        return f"[[views/readers/{metadata['id']}|{self._title(metadata)}]]"

    def _extraction(self, source_id: str) -> tuple[dict[str, Any] | None, str]:
        try:
            _, metadata, body = self.extractions.latest_for_source(source_id)
            return metadata, body
        except Exception:
            return None, ""

    def _reader(self, source_path: Path, metadata: dict[str, Any], source_body: str) -> str:
        extraction, body = self._extraction(str(metadata["id"]))
        content = body.strip()
        if not content:
            # Source bodies contain a bounded preview. They are preferable to an empty reader,
            # but are clearly labelled because they are not a ready extraction.
            content = source_body.strip()
        title = self._title(metadata)
        lines = [self._header(title, "自动生成的阅读视图；原始资料与审计记录保持不变。")]
        lines.append("## 资料信息\n\n")
        lines.append(f"- 来源：{metadata.get('source_kind', 'unknown')}\n")
        if metadata.get("author"):
            lines.append(f"- 作者：{metadata['author']}\n")
        lines.append(f"- 发布/收录：{self._date(metadata)}\n")
        if metadata.get("original_locator"):
            lines.append(f"- 原文：[打开链接]({metadata['original_locator']})\n")
        lines.append(f"- 审计记录：{self._link(source_path, metadata)}\n")
        state = "已提取正文" if extraction else "仅有来源预览"
        lines.append(f"- 阅读状态：{state}\n\n")
        lines.append("## 正文\n\n")
        lines.append(content or "目前没有可读正文。可在下次 daily 中重新提取。")
        lines.append("\n")
        return "".join(lines)

    def render(self) -> dict[str, str]:
        documents = self._documents()
        sources = self._sources()
        rendered: dict[str, str] = {}

        by_type: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
        partial: list[tuple[Path, dict[str, Any]]] = []
        stale: list[tuple[Path, dict[str, Any]]] = []
        for path, metadata in documents:
            by_type[str(metadata.get("type", "unknown"))].append((path, metadata))
            if metadata.get("type") == "claim" and metadata.get("evidence_coverage") in {"partial", "missing"}:
                partial.append((path, metadata))
            if metadata.get("status") in {"contested", "superseded", "archived"} or metadata.get("stale_reason"):
                stale.append((path, metadata))

        pending = []
        for path in self.repository.proposal_documents():
            metadata, _ = read_document(path)
            if metadata.get("status") in {"pending", "deferred"}:
                pending.append((metadata, path))
        pending.sort(key=lambda item: str(item[0].get("created_at") or item[0].get("id") or ""), reverse=True)

        home = [self._header("超级大脑", "从这里阅读资料、回顾近期变化，并进入已经确认的知识。")]
        home.append("## 快速入口\n\n")
        home.extend([
            "- [[views/最近导入|最近导入]] — 刚加入、尚未深加工的资料\n",
            "- [[views/资料库|资料库]] — 按来源浏览全部文章\n",
            "- [[views/主题导航|主题导航]] — 按主题和领域进入\n",
            "- [[views/知识目录|知识目录]] — 已进入 canonical 的知识\n",
            "- [[views/待深挖|待深挖]] — 需要复核、补证据或后续处理\n",
            "- [[views/Review Queues|审阅队列（技术视图）]]\n\n",
        ])
        home.append("## 当前概况\n\n")
        home.append(f"- 资料：{len(sources)} 篇\n- Canonical 知识：{len(documents)} 条\n- 待审阅 proposal：{len(pending)} 项\n\n")
        home.append("## 最近收录\n\n")
        home.extend(f"- {self._reader_link(metadata)} · {self._date(metadata)}\n" for _, metadata, _ in sources[:8])
        if not sources:
            home.append("- 暂无资料\n")
        rendered["vault/INDEX.md"] = "".join(home)

        recent = [self._header("最近导入", "新资料先低成本进入这里；daily/weekly 会逐步整理。")]
        for _, metadata, _ in sources[:30]:
            recent.append(f"- {self._reader_link(metadata)} · {self._date(metadata)} · `{metadata.get('source_kind', 'unknown')}`\n")
        if not sources:
            recent.append("暂无资料。\n")
        rendered["vault/views/最近导入.md"] = "".join(recent)

        by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for _, metadata, _ in sources:
            by_kind[str(metadata.get("source_kind") or "其他")].append(metadata)
        library = [self._header("资料库", "所有来源的可读入口；收录不等于观点已被确认。")]
        for kind in sorted(by_kind):
            library.append(f"## {kind}（{len(by_kind[kind])}）\n\n")
            library.extend(f"- {self._reader_link(item)} · {self._date(item)}\n" for item in by_kind[kind])
            library.append("\n")
        rendered["vault/views/资料库.md"] = "".join(library)

        topics: dict[str, list[tuple[str, dict[str, Any]]]] = defaultdict(list)
        for _, metadata, _ in sources:
            labels = [str(value) for value in [*metadata.get("domains", []), *metadata.get("tags", [])] if value]
            for label in labels or [str(metadata.get("source_kind") or "未分类")]:
                topics[label].append(("source", metadata))
        for path, metadata in documents:
            labels = [str(value) for value in [*metadata.get("domains", []), *metadata.get("tags", [])] if value]
            for label in labels:
                topics[label].append((self.repository.rel(path), metadata))
        topic_lines = [self._header("主题导航", "主题来自已有 tags/domains；没有自动推断或虚构分类。")]
        for topic in sorted(topics):
            topic_lines.append(f"## {topic}\n\n")
            seen: set[str] = set()
            for location, metadata in topics[topic]:
                item_id = str(metadata.get("id"))
                if item_id in seen:
                    continue
                seen.add(item_id)
                if location == "source":
                    topic_lines.append(f"- {self._reader_link(metadata)}\n")
                else:
                    topic_lines.append(f"- {self._link(self.repository.root / location, metadata)}\n")
            topic_lines.append("\n")
        rendered["vault/views/主题导航.md"] = "".join(topic_lines)

        catalog = [self._header("知识目录", "这里只列 canonical 对象；资料收录与知识确认保持分层。")]
        for object_type in sorted(by_type):
            catalog.append(f"## {object_type}\n\n")
            catalog.extend(f"- {self._link(path, metadata)} · `{metadata.get('status', 'unknown')}`\n" for path, metadata in by_type[object_type])
            catalog.append("\n")
        if not documents:
            catalog.append("目前还没有 canonical 知识。\n")
        rendered["vault/views/知识目录.md"] = "".join(catalog)
        # Keep the old stable entry working for existing links and agent adapters.
        rendered["vault/views/Knowledge Catalog.md"] = "".join(catalog)

        deep = [self._header("待深挖", "这里是工作队列，不代表内容已经成立。")]
        deep.append(f"## 待审阅 proposal（{len(pending)}）\n\n")
        deep.extend(f"- {metadata.get('title') or metadata.get('id')} · `{metadata.get('status')}`\n" for metadata, _ in pending)
        deep.append(f"\n## 证据不完整（{len(partial)}）\n\n")
        deep.extend(f"- {self._link(path, metadata)}\n" for path, metadata in partial)
        deep.append(f"\n## 历史或状态变化（{len(stale)}）\n\n")
        deep.extend(f"- {self._link(path, metadata)}\n" for path, metadata in stale)
        rendered["vault/views/待深挖.md"] = "".join(deep)

        review = [self._header("Review Queues", "供 Agent 与治理检查使用的技术队列。")]
        review.append(f"## Pending proposals ({len(pending)})\n\n")
        review.extend(f"- `{metadata.get('id')}` — {metadata.get('title')} (`{self.repository.rel(path)}`)\n" for metadata, path in pending)
        review.append(f"\n## Partial evidence ({len(partial)})\n\n")
        review.extend(f"- {self._link(path, metadata)}\n" for path, metadata in partial)
        review.append(f"\n## Stale or historical ({len(stale)})\n\n")
        review.extend(f"- {self._link(path, metadata)}\n" for path, metadata in stale)
        rendered["vault/views/Review Queues.md"] = "".join(review)

        for source_path, metadata, source_body in sources:
            rendered[self._reader_relative(str(metadata["id"]))] = self._reader(source_path, metadata, source_body)
        return rendered

    def status(self) -> dict[str, Any]:
        rendered = self.render()
        missing, stale = [], []
        for relative, expected in rendered.items():
            path = self.repository.root / relative
            if not path.exists():
                missing.append(relative)
            elif path.read_text(encoding="utf-8") != expected:
                stale.append(relative)
        return {"current": not missing and not stale, "missing": missing, "stale": stale}

    def build(self) -> dict[str, Any]:
        rendered = self.render()
        for relative, content in rendered.items():
            atomic_write_text(self.repository.root / relative, content)
        readers = self.repository.root / "vault" / "views" / "readers"
        removed: list[str] = []
        if readers.exists():
            expected = {(self.repository.root / relative).resolve() for relative in rendered if "/readers/" in relative}
            for path in readers.glob("*.md"):
                if path.resolve() not in expected and f"generated by {GENERATOR}" in path.read_text(encoding="utf-8")[:200]:
                    removed.append(self.repository.rel(path))
                    path.unlink()
        return {"ok": True, "documents": len(self._documents()), "sources": len(self._sources()), "written": list(rendered), "removed": removed}
