from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
import re
from typing import Any

from .extraction import ExtractionService
from .markdown import atomic_write_text, read_document
from .repository import Repository


GENERATOR = "gm-obsidian-v2"


class ObsidianViewService:
    """Build disposable, human-readable Obsidian views without changing truth layers."""

    def __init__(self, repository: Repository):
        self.repository = repository
        self.extractions = ExtractionService(repository)

    def _documents(self) -> list[tuple[Path, dict[str, Any]]]:
        documents = [
            (path, read_document(path)[0])
            for path in [*self.repository.memory_documents(), *self.repository.canonical_documents()]
        ]
        return sorted(documents, key=lambda item: (str(item[1].get("type", "")), self._title(item[1])))

    def _cognitive_syntheses(self) -> list[tuple[Path, dict[str, Any]]]:
        documents = [
            (path, read_document(path)[0])
            for path in self.repository.synthesis_documents()
        ]
        return sorted(documents, key=lambda item: self._title(item[1]))

    @staticmethod
    def _operational_graph_artifact(metadata: dict[str, Any]) -> bool:
        return (
            metadata.get("type") == "experiment"
            and (
                "agent-acceptance" in metadata.get("tags", [])
                or "global-memory" in metadata.get("domains", [])
            )
        )

    def _sources(self) -> list[tuple[Path, dict[str, Any], str]]:
        sources = []
        for path in self.repository.source_documents():
            metadata, body = read_document(path)
            sources.append((path, metadata, body))
        return sorted(
            sources,
            key=lambda item: str(item[1].get("captured_at") or item[1].get("created_at") or ""),
            reverse=True,
        )

    @staticmethod
    def _title(metadata: dict[str, Any]) -> str:
        return str(metadata.get("title") or metadata.get("original_title") or metadata.get("id") or "未命名")

    def _link(self, path: Path, metadata: dict[str, Any]) -> str:
        relative = self.repository.rel(path).removeprefix("vault/").removesuffix(".md")
        return f"[[{relative}|{self._title(metadata)}]]"

    @staticmethod
    def _header(title: str, description: str = "") -> str:
        lead = f"# {title}\n\n"
        if description:
            lead += f"> {description}\n\n"
        return f"<!-- generated by {GENERATOR}; safe to rebuild -->\n\n{lead}"

    @staticmethod
    def _date(metadata: dict[str, Any]) -> str:
        value = str(metadata.get("published_at") or metadata.get("captured_at") or metadata.get("created_at") or "")
        return value[:10] or "日期未知"

    @staticmethod
    def _reader_relative(source_id: str) -> str:
        return f"vault/views/readers/{source_id}.md"

    def _reader_link(self, metadata: dict[str, Any]) -> str:
        return f"[[views/readers/{metadata['id']}|{self._title(metadata)}]]"

    @staticmethod
    def _graph_filename(title: str, fallback: str) -> str:
        clean = re.sub(r'[<>:"/\\|?*\x00-\x1f]', " ", title)
        clean = re.sub(r"\s+", " ", clean).strip(" .")
        return (clean or fallback)[:72].rstrip(" .")

    @staticmethod
    def _graph_category(object_type: str) -> str:
        return {
            "claim": "claims", "concept": "concepts", "work": "works",
            "question": "questions", "tension": "tensions",
            "hypothesis": "hypotheses", "analogy": "analogies",
            "synthesis": "syntheses",
            "project": "projects", "experiment": "experiments",
            "opportunity": "opportunities",
        }.get(object_type, "other")

    def _graph_display_title(self, metadata: dict[str, Any]) -> str:
        """Keep compact method aliases visible without exposing internal IDs."""
        title = self._title(metadata)
        if metadata.get("type") != "concept":
            return title
        aliases = metadata.get("aliases", [])
        if not isinstance(aliases, list):
            return title
        method_alias = next((
            str(alias).strip() for alias in aliases
            if isinstance(alias, str)
            and 1 < len(alias.strip()) <= 24
            and re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9 .+_/()-]*", alias.strip())
            and (
                any(char.isupper() for char in alias.strip()[1:])
                or any(char.isdigit() for char in alias.strip())
                or "-" in alias.strip()
            )
        ), "")
        if not method_alias or method_alias.casefold() in title.casefold():
            return title
        return f"{method_alias} · {title}"

    def _semantic_graph(
        self,
        documents: list[tuple[Path, dict[str, Any]]],
        sources: list[tuple[Path, dict[str, Any], str]],
    ) -> dict[str, str]:
        """Render a human-labelled graph mirror from structured relations/source_ids."""
        rendered: dict[str, str] = {}
        locations: dict[str, str] = {}
        metadata_by_id: dict[str, dict[str, Any]] = {}
        display_titles: dict[str, str] = {}
        used: set[str] = set()

        source_referrers: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for _, metadata in documents:
            for source_id in metadata.get("source_ids", []):
                source_referrers[str(source_id)].append(metadata)

        def source_title(metadata: dict[str, Any]) -> str:
            title = self._title(metadata)
            # Capture tools sometimes only know the host name. In the graph, prefer
            # the associated work/object title so humans do not see a wall of domains.
            if re.fullmatch(r"[\w.-]+\.[A-Za-z]{2,}", title):
                referrers = source_referrers.get(str(metadata["id"]), [])
                preferred = next(
                    (item for item in referrers if item.get("type") == "work"),
                    referrers[0] if referrers else None,
                )
                if preferred:
                    return f"{self._title(preferred)}（原始资料）"
                original_filename = str(metadata.get("original_filename") or "")
                if original_filename:
                    return f"{Path(original_filename).stem}（原始资料）"
            return title

        def allocate(item_id: str, title: str, category: str) -> str:
            filename = self._graph_filename(title, item_id)
            key = f"{category}/{filename}".casefold()
            duplicate = 2
            while key in used:
                suffix = f"（{duplicate}）"
                filename = f"{filename[:72 - len(suffix)].rstrip()}{suffix}"
                key = f"{category}/{filename}".casefold()
                duplicate += 1
            used.add(key)
            return f"vault/views/graph/{category}/{filename}.md"

        for _, metadata, _ in sources:
            item_id = str(metadata["id"])
            display_titles[item_id] = source_title(metadata)
            locations[item_id] = allocate(item_id, display_titles[item_id], "sources")
            metadata_by_id[item_id] = metadata
        for _, metadata in documents:
            item_id = str(metadata["id"])
            category = self._graph_category(str(metadata.get("type", "other")))
            display_titles[item_id] = self._graph_display_title(metadata)
            locations[item_id] = allocate(item_id, display_titles[item_id], category)
            metadata_by_id[item_id] = metadata

        incoming: dict[str, set[str]] = defaultdict(set)
        for _, metadata in documents:
            source_id = str(metadata["id"])
            cognitive_targets = (
                [str(item) for item in metadata.get("input_concepts", [])]
                if metadata.get("type") == "synthesis"
                else []
            )
            for target_id in [
                *[str(item) for item in metadata.get("source_ids", [])],
                *cognitive_targets,
                *[
                    str(relation.get("target_id"))
                    for relation in metadata.get("relations", [])
                    if isinstance(relation, dict) and relation.get("target_id")
                ],
            ]:
                if target_id in locations and target_id != source_id:
                    incoming[target_id].add(source_id)

        for item_id, relative in locations.items():
            metadata = metadata_by_id[item_id]
            title = display_titles[item_id]
            lines = [self._header(title, "人类可读的派生语义图节点；真实内容与治理状态仍以原对象为准。")]
            original_path, _, _ = self.repository.find_document(item_id)
            lines.append(f"- 原始对象：`{self.repository.rel(original_path)}`\n")
            lines.append(f"- 类型：`{metadata.get('type', 'source')}`\n")
            if metadata.get("memory_tier") or metadata.get("status"):
                lines.append(f"- 状态：`{metadata.get('memory_tier') or metadata.get('status')}`\n")
            links: list[tuple[str, str]] = []
            for source_id in metadata.get("source_ids", []):
                source_id = str(source_id)
                if source_id in locations and source_id != item_id:
                    links.append((source_id, "来源"))
            for relation in metadata.get("relations", []):
                if not isinstance(relation, dict):
                    continue
                target_id = str(relation.get("target_id") or "")
                if target_id in locations and target_id != item_id:
                    links.append((target_id, str(relation.get("type") or "关联")))
            if metadata.get("type") == "synthesis":
                for target_id in metadata.get("input_concepts", []):
                    target_id = str(target_id)
                    if target_id in locations and target_id != item_id:
                        links.append((target_id, "综合输入（非事实关系）"))
            for child_id in sorted(incoming.get(item_id, set())):
                links.append((child_id, "被引用"))
            if links:
                lines.append("\n## 语义连接\n\n")
                seen_links: set[str] = set()
                for target_id, relation_type in links:
                    if target_id in seen_links:
                        continue
                    seen_links.add(target_id)
                    target = locations[target_id].removeprefix("vault/").removesuffix(".md")
                    target_title = display_titles[target_id]
                    lines.append(f"- `{relation_type}` → [[{target}|{target_title}]]\n")
            rendered[relative] = "".join(lines)
        return rendered

    def _extraction(self, source_id: str) -> tuple[dict[str, Any] | None, str]:
        try:
            _, metadata, body = self.extractions.latest_for_source(source_id)
            return metadata, body
        except Exception:
            return None, ""

    def _reader(self, source_path: Path, metadata: dict[str, Any], source_body: str) -> str:
        extraction, body = self._extraction(str(metadata["id"]))
        content = body.strip()
        if not content:
            # Source bodies contain a bounded preview. They are preferable to an empty reader,
            # but are clearly labelled because they are not a ready extraction.
            content = source_body.strip()
        title = self._title(metadata)
        lines = [self._header(title, "自动生成的阅读视图；原始资料与审计记录保持不变。")]
        lines.append("## 资料信息\n\n")
        lines.append(f"- 来源：{metadata.get('source_kind', 'unknown')}\n")
        if metadata.get("author"):
            lines.append(f"- 作者：{metadata['author']}\n")
        lines.append(f"- 发布/收录：{self._date(metadata)}\n")
        if metadata.get("original_locator"):
            lines.append(f"- 原文：[打开链接]({metadata['original_locator']})\n")
        lines.append(f"- 审计记录：{self._link(source_path, metadata)}\n")
        state = "已提取正文" if extraction else "仅有来源预览"
        lines.append(f"- 阅读状态：{state}\n\n")
        lines.append("## 正文\n\n")
        lines.append(content or "目前没有可读正文。可在下次 daily 中重新提取。")
        lines.append("\n")
        return "".join(lines)

    def render(self, *, graph_profile: str = "knowledge") -> dict[str, str]:
        if graph_profile not in {"knowledge", "trusted", "frontier", "all"}:
            raise ValueError("graph_profile must be knowledge, trusted, frontier, or all")
        documents = self._documents()
        cognitive_syntheses = self._cognitive_syntheses()
        sources = self._sources()
        rendered: dict[str, str] = {}
        if graph_profile == "all":
            graph_documents = [*documents, *cognitive_syntheses]
        elif graph_profile == "knowledge":
            # Human default: show active semantic objects, including model-distilled
            # Working memory, but keep raw Sources out of the graph. Provenance stays
            # available in each projected node and in the reader/audit views.
            graph_documents = [
                item for item in documents
                if item[1].get("memory_tier") != "historical"
                and item[1].get("status") not in {"archived", "superseded"}
                and item[1].get("type") in {
                    "claim", "concept", "question", "tension", "hypothesis", "analogy",
                    "architecture", "experiment", "synthesis", "opportunity",
                }
                and not self._operational_graph_artifact(item[1])
            ]
            graph_documents.extend(
                item for item in cognitive_syntheses
                if item[1].get("status") == "active"
                and item[1].get("truth_layer") == "cognitive_synthesis"
            )
        elif graph_profile == "frontier":
            graph_documents = [
                item for item in documents
                if item[1].get("type") in {"question", "tension", "hypothesis", "analogy", "concept"}
            ]
        else:
            graph_documents = [
                item for item in documents
                if item[1].get("memory_tier") in {"trusted", "canonical"}
                or item[1].get("type") in {"question", "tension"}
            ]
        graph_source_ids = {
            str(source_id) for _, metadata in graph_documents
            for source_id in metadata.get("source_ids", [])
        }
        if graph_profile == "all":
            graph_sources = sources
        elif graph_profile == "knowledge":
            graph_sources = []
        else:
            graph_sources = [
                item for item in sources if str(item[1]["id"]) in graph_source_ids
            ]
        rendered.update(self._semantic_graph(graph_documents, graph_sources))

        by_type: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
        partial: list[tuple[Path, dict[str, Any]]] = []
        stale: list[tuple[Path, dict[str, Any]]] = []
        for path, metadata in documents:
            by_type[str(metadata.get("type", "unknown"))].append((path, metadata))
            if metadata.get("type") == "claim" and metadata.get("evidence_coverage") in {"partial", "missing"}:
                partial.append((path, metadata))
            if metadata.get("status") in {"contested", "superseded", "archived"} or metadata.get("stale_reason"):
                stale.append((path, metadata))

        pending = []
        for path in self.repository.proposal_documents():
            metadata, _ = read_document(path)
            if metadata.get("status") in {"pending", "deferred"}:
                pending.append((metadata, path))
        pending.sort(key=lambda item: str(item[0].get("created_at") or item[0].get("id") or ""), reverse=True)
        source_only = []
        for path in self.repository.proposal_documents():
            metadata, _ = read_document(path)
            if metadata.get("status") == "source_only" or metadata.get("compile_disposition") == "source_only":
                source_only.append((metadata, path))
        source_only.sort(key=lambda item: str(item[0].get("created_at") or item[0].get("id") or ""), reverse=True)

        source_only_lines = [self._header("Source-only 资料", "已成功保存、可检索，但尚未安全编译为知识对象的原始资料。")]
        for metadata, path in source_only:
            source_id = next(iter(metadata.get("source_only_source_ids", metadata.get("source_ids", []))), None)
            if source_id:
                try:
                    _, source_metadata, _ = self.repository.find_document(str(source_id))
                    title = self._reader_link(source_metadata)
                except Exception:
                    title = str(source_id)
            else:
                title = str(metadata.get("title", metadata.get("id")))
            reason = "; ".join(map(str, metadata.get("low_value_items_not_proposed", []))) or str(metadata.get("review_reason", ""))
            source_only_lines.append(f"- {title} — {reason or 'source-only'}\n")
        if not source_only:
            source_only_lines.append("- 暂无 source-only 资料。\n")
        rendered["vault/views/Source-only 资料.md"] = "".join(source_only_lines)

        exceptions = []
        exception_dir = self.repository.root / "vault" / "exceptions"
        for path in sorted(exception_dir.glob("exception-*.md")) if exception_dir.exists() else []:
            metadata, _ = read_document(path)
            if metadata.get("status") in {"open", "deferred"}:
                exceptions.append((path, metadata))
        promotions = []
        promotion_dir = self.repository.root / "vault" / "promotions"
        for path in sorted(promotion_dir.glob("promotion-*.md")) if promotion_dir.exists() else []:
            metadata, _ = read_document(path)
            if metadata.get("status") in {"pending", "deferred"}:
                promotions.append((path, metadata))

        home = [self._header("超级大脑", "从这里阅读资料、回顾近期变化，并进入已经确认的知识。")]
        home.append("## 快速入口\n\n")
        home.extend([
            "- [[views/最近导入|最近导入]] — 刚加入、尚未深加工的资料\n",
            "- [[views/资料库|资料库]] — 按来源浏览全部文章\n",
            "- [[views/主题导航|主题导航]] — 按主题和领域进入\n",
            "- [[views/知识目录|知识目录]] — 已进入 canonical 的知识\n",
            "- [[views/待深挖|待深挖]] — 需要复核、补证据或后续处理\n",
            "- [[views/记忆层级|记忆层级]] — 浏览 Working / Trusted / Canonical\n",
            "- [[views/例外队列|例外队列]] · [[views/晋升队列|晋升队列]] · [[views/每周整合|每周整合]]\n",
            "- [[views/Review Queues|审阅队列（技术视图）]]\n\n",
        ])
        home.append("## 当前概况\n\n")
        tier_counts = Counter(str(metadata.get("memory_tier") or metadata.get("status")) for _, metadata in documents)
        home.append(
            f"- 资料：{len(sources)} 篇\n- Working：{tier_counts.get('working', 0)} 条\n"
            f"- Trusted：{tier_counts.get('trusted', 0)} 条\n- Canonical："
            f"{sum(1 for path, _ in documents if self.repository.rel(path).startswith(('vault/knowledge/', 'vault/frontier/', 'vault/action/')))} 条\n"
            f"- 开放例外：{len(exceptions)} 项\n- 待确认晋升：{len(promotions)} 项\n\n"
        )
        home.append("## 最近收录\n\n")
        home.extend(f"- {self._reader_link(metadata)} · {self._date(metadata)}\n" for _, metadata, _ in sources[:8])
        if not sources:
            home.append("- 暂无资料\n")
        rendered["vault/INDEX.md"] = "".join(home)

        recent = [self._header("最近导入", "新资料先低成本进入这里；daily/weekly 会逐步整理。")]
        for _, metadata, _ in sources[:30]:
            recent.append(f"- {self._reader_link(metadata)} · {self._date(metadata)} · `{metadata.get('source_kind', 'unknown')}`\n")
        if not sources:
            recent.append("暂无资料。\n")
        rendered["vault/views/最近导入.md"] = "".join(recent)

        by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for _, metadata, _ in sources:
            by_kind[str(metadata.get("source_kind") or "其他")].append(metadata)
        library = [self._header("资料库", "所有来源的可读入口；收录不等于观点已被确认。")]
        for kind in sorted(by_kind):
            library.append(f"## {kind}（{len(by_kind[kind])}）\n\n")
            library.extend(f"- {self._reader_link(item)} · {self._date(item)}\n" for item in by_kind[kind])
            library.append("\n")
        rendered["vault/views/资料库.md"] = "".join(library)

        topics: dict[str, list[tuple[str, dict[str, Any]]]] = defaultdict(list)
        for _, metadata, _ in sources:
            labels = [str(value) for value in [*metadata.get("domains", []), *metadata.get("tags", [])] if value]
            for label in labels or [str(metadata.get("source_kind") or "未分类")]:
                topics[label].append(("source", metadata))
        for path, metadata in documents:
            labels = [str(value) for value in [*metadata.get("domains", []), *metadata.get("tags", [])] if value]
            for label in labels:
                topics[label].append((self.repository.rel(path), metadata))
        topic_lines = [self._header("主题导航", "主题来自已有 tags/domains；没有自动推断或虚构分类。")]
        for topic in sorted(topics):
            topic_lines.append(f"## {topic}\n\n")
            seen: set[str] = set()
            for location, metadata in topics[topic]:
                item_id = str(metadata.get("id"))
                if item_id in seen:
                    continue
                seen.add(item_id)
                if location == "source":
                    topic_lines.append(f"- {self._reader_link(metadata)}\n")
                else:
                    topic_lines.append(f"- {self._link(self.repository.root / location, metadata)}\n")
            topic_lines.append("\n")
        rendered["vault/views/主题导航.md"] = "".join(topic_lines)

        catalog = [self._header("知识目录", "按对象类型列出可用记忆；每条保留 Working / Trusted / Canonical 状态。")]
        for object_type in sorted(by_type):
            catalog.append(f"## {object_type}\n\n")
            catalog.extend(f"- {self._link(path, metadata)} · `{metadata.get('status', 'unknown')}`\n" for path, metadata in by_type[object_type])
            catalog.append("\n")
        if not documents:
            catalog.append("目前还没有 canonical 知识。\n")
        rendered["vault/views/知识目录.md"] = "".join(catalog)
        # Keep the old stable entry working for existing links and agent adapters.
        rendered["vault/views/Knowledge Catalog.md"] = "".join(catalog)

        tiers: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
        for path, metadata in documents:
            tier = str(metadata.get("memory_tier") or (
                "canonical" if self.repository.rel(path).startswith(("vault/knowledge/", "vault/frontier/", "vault/action/"))
                else metadata.get("status", "working")
            ))
            tiers[tier].append((path, metadata))
        tier_lines = [self._header("记忆层级", "Working 可用但可变，Trusted 已通过整合策略，Canonical 只由人确认。")]
        for tier in ("working", "trusted", "canonical"):
            items = tiers.get(tier, [])
            tier_lines.append(f"## {tier.title()}（{len(items)}）\n\n")
            tier_lines.extend(f"- {self._link(path, metadata)} · `{metadata.get('type')}`\n" for path, metadata in items)
            tier_lines.append("\n")
        rendered["vault/views/记忆层级.md"] = "".join(tier_lines)

        exception_lines = [self._header("例外队列", "只有冲突、证据不足、复合主张或高影响变更才进入人工处理。")]
        exception_lines.extend(
            f"- {self._link(path, metadata)} · `{metadata.get('severity')}` · {', '.join(metadata.get('reasons', []))}\n"
            for path, metadata in exceptions
        )
        if not exceptions:
            exception_lines.append("当前没有开放例外。\n")
        rendered["vault/views/例外队列.md"] = "".join(exception_lines)

        promotion_lines = [self._header("晋升队列", "这里仅显示需要你决定是否进入 Canonical 的高影响记忆。")]
        promotion_lines.extend(
            f"- {self._link(path, metadata)} · 对象 `{metadata.get('object_id')}`\n"
            for path, metadata in promotions
        )
        if not promotions:
            promotion_lines.append("当前没有待确认晋升。\n")
        rendered["vault/views/晋升队列.md"] = "".join(promotion_lines)

        reports = sorted((self.repository.root / "system" / "reports").glob("generated-weekly_*.md"), reverse=True)
        weekly_lines = [self._header("每周整合", "Weekly consolidation 的压缩率、晋升、保留与例外摘要。")]
        weekly_lines.extend(f"- `{self.repository.rel(path)}`\n" for path in reports[:12])
        if not reports:
            weekly_lines.append("尚未生成每周整合报告。\n")
        rendered["vault/views/每周整合.md"] = "".join(weekly_lines)

        deep = [self._header("待深挖", "这里是工作队列，不代表内容已经成立。")]
        deep.append(f"## 待审阅 proposal（{len(pending)}）\n\n")
        deep.extend(f"- {metadata.get('title') or metadata.get('id')} · `{metadata.get('status')}`\n" for metadata, _ in pending)
        deep.append(f"\n## 证据不完整（{len(partial)}）\n\n")
        deep.extend(f"- {self._link(path, metadata)}\n" for path, metadata in partial)
        deep.append(f"\n## 历史或状态变化（{len(stale)}）\n\n")
        deep.extend(f"- {self._link(path, metadata)}\n" for path, metadata in stale)
        rendered["vault/views/待深挖.md"] = "".join(deep)

        review = [self._header("Review Queues", "供 Agent 与治理检查使用的技术队列。")]
        review.append(f"## Pending proposals ({len(pending)})\n\n")
        review.extend(f"- `{metadata.get('id')}` — {metadata.get('title')} (`{self.repository.rel(path)}`)\n" for metadata, path in pending)
        review.append(f"\n## Partial evidence ({len(partial)})\n\n")
        review.extend(f"- {self._link(path, metadata)}\n" for path, metadata in partial)
        review.append(f"\n## Stale or historical ({len(stale)})\n\n")
        review.extend(f"- {self._link(path, metadata)}\n" for path, metadata in stale)
        rendered["vault/views/Review Queues.md"] = "".join(review)

        for source_path, metadata, source_body in sources:
            rendered[self._reader_relative(str(metadata["id"]))] = self._reader(source_path, metadata, source_body)
        return rendered

    def status(self, *, graph_profile: str = "knowledge") -> dict[str, Any]:
        rendered = self.render(graph_profile=graph_profile)
        missing, stale = [], []
        for relative, expected in rendered.items():
            path = self.repository.root / relative
            if not path.exists():
                missing.append(relative)
            elif path.read_text(encoding="utf-8") != expected:
                stale.append(relative)
        return {"current": not missing and not stale, "missing": missing, "stale": stale}

    def build(self, *, graph_profile: str = "knowledge") -> dict[str, Any]:
        rendered = self.render(graph_profile=graph_profile)
        for relative, content in rendered.items():
            atomic_write_text(self.repository.root / relative, content)
        readers = self.repository.root / "vault" / "views" / "readers"
        removed: list[str] = []
        if readers.exists():
            expected = {(self.repository.root / relative).resolve() for relative in rendered if "/readers/" in relative}
            for path in readers.glob("*.md"):
                if path.resolve() not in expected and f"generated by {GENERATOR}" in path.read_text(encoding="utf-8")[:200]:
                    removed.append(self.repository.rel(path))
                    path.unlink()
        graph = self.repository.root / "vault" / "views" / "graph"
        if graph.exists():
            expected = {(self.repository.root / relative).resolve() for relative in rendered if "/graph/" in relative}
            for path in graph.rglob("*.md"):
                if path.resolve() not in expected and f"generated by {GENERATOR}" in path.read_text(encoding="utf-8")[:200]:
                    removed.append(self.repository.rel(path))
                    path.unlink()
        return {"ok": True, "graph_profile": graph_profile, "documents": len(self._documents()), "sources": len(self._sources()), "written": list(rendered), "removed": removed}
